name = "memos-worker"
compatibility_date = "2025-08-19"
main = "src/index.js"
[assets]
directory = "./src/public"
run_worker_first = [
	"/api/*"
]

[[d1_databases]]
binding = "DB"
database_id = "7f54b5c0-5d3c-4a1f-b910-c4f4948de5dc"
database_name = "notes-db"

[[kv_namespaces]]
binding = "NOTES_KV"
id = "826455a86e964b6aa16da0678d657fe9"
preview_id = ""

[[r2_buckets]]
binding = "NOTES_R2_BUCKET"
bucket_name = "notes-r2-bucket"
preview_bucket_name = "notes-files-preview"
